#!/bin/bash

actors=(
    "Leonardo_DiCaprio"
    "Jessica_Lange"
    "Joe_Pesci"
    "Jodie_Foster"
    "Bridget_Fonda"
    "Jane_Fonda"
    "Louis_Theroux"
    "Tom_Cruise"
    "Helen_Hunt"
    "Helen_Mirren"
    "Werner_Herzog"
    "Kirsten_Dunst"
    "John_C._Reilly"
    "Jennifer_Lawrence"
    "Joseph_Gordon-Levitt"
    "Meryl_Streep"
    "Julianne_Moore"
    "Brad_Pitt"
    "Christina_Hendricks"
    "Tom_Hardy"
    "Angelina_Jolie"
    "Kevin_Spacey"
    "Kurt_Russel"
    "Russel_Crowe"
    "Scarlett_Johansson"
    "Cameron_Diaz"
    "Kate_Winslett"
    "Susan_Sarandon"
    "Emma_Watson"
    "Emily_Blunt"
    "Kelly_Macdonald"
    "Maggie_Smith"
    "Emma_Thompson"
    "Michael_Gambon"
    "Charles_Dance"
    "Clive_Owen"
    "Emily_Watson"
    "Paul_Newman"
    "Charlotte_Rampling"
    "Gene_Hackman"
    "Kirstie_Alley"
    "Catherine_Zeta-Jones"
    "Naomi_Watts"
    "Helena_Bonham_Carter"
    "Laura_Harring"
    "John_Goodman"
    "Gary_Oldman"
    "Colin_Farrel"
    "Forest_Whitaker"
    "Daniel_Radcliffe"
    "Elijah_Wood"
    "Denzel_Washington"
    "Tom_Hanks"
    "Henry_Fonda"
    "Michael_Caine"
    "Daniel_Craig"
    "Richard_Gere"
    "Julia_Roberts"
    "Liam_Neeson"
    "Ben_Kingsley"
    "Ralph_Fiennes"
    "Nicole_Kidman"
    "Sigourney_Weaver"
    "Ellen_Page"
    "Ken_Watanabe"
    "Cillian_Murphy"
    "Toshiro_Mifune"
    "Ian_McKellen"
    "Pierce_Brosnan"
    "Roger_Moore"
    "Danny_Glover"
    "Kirk_Douglas"
    "Michael_Douglas"
    "Will_Ferrel"
    "Jessica_Lange"
    "Gillian_Anderson"
    "Anne_Hathaway"
    "John_Lithgow"
    "John_Hurt"
    "Mads_Mikkelsen"
    "Peter_O'Toole"
    "Christopher_Plummer"
    "Tim_Roth"
    "Tim_Robbins"
    "Morgan_Freeman"
    "Franka_Potente"
    "Jürgen_Prochnow"
    "Kathy_Bates"
    "Robert_Duvall"
    "Shelley_Duvall"
    "Jack_Nicholson"
    "Al_Pacino"
    "Harvey_Keitel"
    "Marlon_Brando"
    "Will_Smith"
    "Ben_Stiller"
    "Robert_De_Niro"
    "Jamie_Lee_Curtis"
    "Arnold_Schwartzenegger"
    "Danny_DeVito"
    "Milla_Jovovich"
    "Vin_Diesel"
    "Dwayne_Johnson"
    "Paul_Walker"
    "Natalie_Portman"
    "Samuel_Jackson"
    "Chiwetel_Ejiofor"
    "Lucy_Liu"
    "Bill_Murray"
    "Sam_Rockwell"
    "Daniel_Day-Lewis"
    "Adrien_Brody"
    "Patrick_Stewart"
    "Antonio_Banderas"
    "Rebecca_Romijn"
    "Danny_Trejo"
    "Benicio_del_Toro"
    "Javier_Bardem"
    "Tommy_Lee_Jones"
    "Josh_Brolin"
    "Woody_Harrelson"
    "Dennis_Hopper"
    "Ben_Mendelsohn"
    "Eva_Green"
    "Christian_Bale"
    "Christopher_Walken"
    "Willem_Dafoe"
    "Audrey_Tautou"
    "Gérard_Depardieu"
    "Matt_Damon"
    "Edward_Norton"
    "John_Malkovich"
    "Johnny_Depp"
    "Michael_Madsen"
    "Mickey_Rourke"
    "Marisa_Tomei"
    "Ed_Harris"
    "Jude_Law"
    "Ethan_Hawke"
    "John_Turturro"
    "Uma_Thurman"
    "Steven_Segal"
    "Monica_Bellucci"
    "Guy_Pearce"
    "Charlton_Heston"
    "Harrison_Ford"
    "Sissy_Spacek"
    "Anne_Bancroft"
    "Gary_Sinise"
    "Kyle_MacLachlan"
    "Elizabeth_Taylor"
    "Richard_Burton"
    "Audrey_Hepburn"
    "Heath_Ledger"
    "Rutger_Hauer"
    "Malcolm_McDowell"
    "Sophia_Loren"
    "Nina_Hartley"
    "Roberto_Benigni"
    "Jon_Voight"
    "Elisabeth_Shue"
    "Jim_Carrey"
    "Michael_Keaton"
    "Geena_Davis"
    "Catherine_O'Hara"
    "Ben_Affleck"
    "Charles_Bronson"
    "Jack_Lemmon"
    "Vince_Vaughn"
    "Hugh_Jackman"    
    "Nick_Nolte"
    "Juliette_Lewis"
    "Gregory_Pack"
    "Clint_Eastwood"
    "Mary-Louise_Parker"
    "Sharon_Stone"
    "Drew_Barrymore"
    "Michelle_Forbes"
    "Whoopi_Goldberg"
    "Dustin_Hoffman"
    "Demi_Moore"
    "Anne_Heche"
    "Warren_Beatty"
    "Annette_Bening"
    "Faye_Dunaway"
    "Steve_Buscemi"
    "Jeff_Bridges"
    "Philip_Seymour_Hoffman"
    "Adam_Sandler"
    "Luis_Guzmán"
    "Roy_Scheider"
    "Richard_Dreyfuss"
    "Billy_Crystal"
    "Meg_Ryan"
    "Carrie_Fisher"
    "Hugh_Laurie"
    "Hugh_Grant"
    "Benedict_Cumberbatch"
    "Gwyneth_Paltrow"
    "Cate_Blanchett"
    "Eric_Bana"
    "Marion_Cotillard"
    "Jeremy_Irons"
    "Mila_Kunis"
    "Travis_Fimmel"
    "Eddie_Redmayne"
    "Kevin_McKidd"
    "Richard_Belzer"
    "Andre_Braugher"
    "Yaphet_Kotto"
    "Amy_Adams"
    "Sasha_Grey"
    "Stoya"
    "Christopher_Lee"
    "Ian_McKellen"
    "Ciarán_Hinds"
    "Ray_Stevenson_(actor)"
    "Jackie_Chan"
    "Bruce_Lee"
    "Chris_Tucker"
    "Bruce_Willis"
    "Eddie_Murphy"
    "Karl_Urban"
    "Sylvester_Stallone"
    "Ryan_Gosling"
    "Keira_Knightley"
    "Nicholas_Cage"
    "Idris_Elba"
    "Halle_Berry"
    "Hugo_Weaving"
    "Bae_Doona"
    "Sean_Bean"
    "James_Dean"
    "James_D'Arcy"
    "Jason_Statham"
    "David_Carradine"
    "Daryl_Hannah"
    "Laura_Dern"
    "Owen_Wilson"
    "Leslie_Nielsen"
    "Ron_Perlman"
    "Jennifer_Love_Hewitt"
    "Jean_Reno"
    "Peta_Wilson"
    "Keanu_Reeves"
    "Winona_Ryder"
    "James_Gandolfini"
    "Edie_Falco"
    "George_Clooney"
    "Roy_Dupuis"
    "Scott_Bakula"
    "Alan_Rickman"
    "Jaime_Murray"
    "Jennifer_Carpenter"
    "Lauren_Holly"
    "Bruno_Ganz"
    "Peter_Dinklage"
    "Lena_Headey"
    "Rory McCann"
    "Natalie_Dormer"
    "Liam_Cunningham"
    "Michelle_Fairley"
    "Carice_van_Houten"
    "Alan_Tudyk"
    "Nathan_Fillion"
    "Gina_Torres"
    "Laurence_Fishburne"
    "Carrie-Anne_Moss"
    "Patrick_Fischler"
    "Renée_Zellweger"
    "Omar_Sharif"
    "Leelee_Sobiesky"
    "Humphrey_Bogart"
    "Maggie_Gyllenhaal"
    "Jake_Gyllenhaal"
    "Mel_Gibson"
    "Colin_Firth"
    "Sarah_Jessica_Parker"
    "Michelle_Pfeiffer"
    "Richard_Harris"
    "Connie_Nielsen"
    "Charlotte_Gainsbourg"
    "Ralf_Möller"
    "Tommy_Flanagan"
    "Sarah_Michelle_Gellar"
    "Joaquin_Phoenix"
    "Tommy_Flanagan"
    "Jennifer_Connelly"
    "Liv_Tyler"
    "Kristin_Scott_Thomas"
    "Madeleine_Stowe"
    "Emma_Stone"
    "Greta_Garbo"
    "Brittany_Murphy"
    "Jessica_Biel"
    "Katharine_Hepburn"
    "Bette_Davis"
    "Ingrid_Bergman"
    "Judy_Dench"
    "Diane_Keaton"
    "Deborah_Kara_Unger"
    "Patricia_Arquette"
    "Christian_Slater"
    "Patricia_Clarkson"
    "Robert_Downey_Jr."
    "Alicia_Vikander"
    "Salma_Hayek"
    "Penélope_Cruz"
    "James_Cagney"
    "James_Stewart"
    "Cary_Grant"
    "Ray_Liotta"
    "Anthony_Hopkins"
    "Asia_Carrera"
    "Patrick_Swayze"
    "Val_Kilmer"
    "Vincent_D'Onofrio"
    "David_Duchovny"
    "Noomi_Rapace"
    "Ian_Holm"
    "Harry_Dean_Stanton"
    "Frank_Langella"
    "Stephen_Lang"
    "Nathalie_Emmanuel"
    "Tobias_Menzies"
    "Maisie_Williams"
    "Nikolaj_Coster-Waldau"
    "Aidan_Gillen"
    "David_Proval"
    "Mädchen_Amick"
    "Sheryl_Lee"
    "Sherilyn_Fenn"
    "Lara_Flynn_Boyle"
    "Linda_Hunt"
    "Linda_Hamilton"
    "Jim_Broadbent"
    "Billy_Drago"
    "Neal_McDonough"
    "Ray_Wise"
    "Michael_Ironside"
    "Peter_Greene"
    "Frank_Vincent"
    "Chris_Evans"
    "Stephen_Dillane"
    "Brian_Cox (actor)"
    "Brendan_Gleeson"
    "Clancy_Brown"
    "Zoe_Saldana"    
    "Thandie_Newton"
    "Michael_K._Williams"
    "Sophie_Turner"
    "Kit_Harrington"   
    "Isaach_de_Bankolé"
    "Paz_de_la_Huerta"
    "Maria_Bello"
    "Rachel_McAdams"
    "David_Bowie"
    "Monica_Bârlădeanu"
    "Marcel_Iureş"
    "Joe_Pantoliano"
    "Tina_Fey"
    "Rita_Hayworth"
    "Til_Schweiger"
    "George_Kennedy"
    "Brian_Dennehy"
    "Gregg_Henry"
    "Eli_Wallach"
    "Brendan_Fraser"
    "Jason_Clarke"
    "Emilia_Clarke"
    "Gilbert_Gottfried"
    "Bruce_Campbell"
    "Keith_David"
    "Thomas_Kretschmann"
    "William_Devane"
    "Kris_Kristofferson"
    "Stellan_Skarsgård"
    "William_Hurt"
    "Jean_Paul_Belmondo"
    "George_C._Scott"
    "Jessica_Chastain"
    "Carey_Mulligan"
    "Bradley_Cooper"
    "Dolph_Lundgren"
    "Saoirse_Ronan"
    "Brent_Spiner"
    "Marcia_Cross"
    "Dana_Delany"
    "Marina_Sirtis"
    "Lee_Van_Cleef"
    "Scott_Eastwood"
    "Dominic_West"
    "Sidney_Poitier"
    "Woody_Allen"
    "Kim_Bassinger"
    "Edward_G._Robinson"   
    "Frank_Sinatra"
    "Max_Von_Sydow"
    "Amanda_Plummer"
    "Sidney_Pollack"
    "Sibel_Kekilli"
    "Alan_Tudyk"
    "Rachel_Weisz"
    "Takashi_Shimura"
    "Jack_Black"
    "John_Cusack"
    "Eva_Longoria"
    "Sara_Jessica_Parker"
    "Buster_Keaton"
    "Chris_Farley"
    "Steven_Van_Zandt"
    "Don_Cheadle"
    "Fred_Astaire"
    "Gary_Cooper"
    "Zack_Galifianakis"
    "Juliette_Binoche"
    "Jennifer_Love_Hewitt"
    "Priscilla_Presley"
    "Victoria_Principal"
    "Patrick_Duffy"
    "Linda_Gray"
    "Larry_Hagman"
    "Julia_Ormond"
    "Frances_McDormand"
    "Hillary_Swank"
    "Gary_Busey"
    "Famke_Jannsen"
    "Victor_Garber"
    "Natalia_Tena"
    "Charlize_Theron"
    "John_Travolta"
    "Mila_Jovovich"
    "Justin_Theroux"
    "Alec_Baldwin"
    "Stephen_Baldwin"
    "Gabriel_Byrne"
    "Alain_Delon"
    "Christopher_MacDonald"
    "Anthony_Quinn"
    "Burt_Lancaster"
    "Donald_Sutherland"
    "Kiefer_Sutherland"
    "Martin_Sheen"
    "Charlie_Sheen"
    "Marlene_Dietrich"
    "Michael_Imperioli"
    "Drea_de_Matteo"
    "Mathew_Broderick"
    "Elizabeth_Perkins"
    "Julie_Andrews"
    "Christina_Applegate"
    "Oscar_Isaac"
    "Steve_Carrel"
    "Ed_O'Neill"
    "David_Faustino"
    "Ava_Gardner"
    "Alan_Alda"
    "Paul_Giamatti"
    "Brad_Dourif"
    "David_Morse"
    "David_Strathairn"
    "Gary_Cole"
    "James_Cromwell"
    "James_Rebhorn"
    "Michael_Peña"
    "Mike_Starr (Actor)"
    "Paul_Dano"
    "William_Fichtner"
    "Bob_Gutnon"
    "J.K._Simmons"
    "Alan_Arkin"
    "David_Bradley"
    "Stephen_Tobolowsky"
    "Mark_Ruffalo"
    "Robbie_Coltrane"
    "Domhnall_Gleeson"
    "Rupert_Grint"
    "Mark_Wahlberg"
    "Jeremy_Renner"
    "Daisy_Ridley"
    "Gwendoline_Christie"
    "Sean_Penn"
    "Rowan_Atkinson"
    "Clark_Gable"
    "Diego_Luna"
    "Morenna_Baccarin"
    "Richard_Chamberlain"
    "Wil_Wheaton"
    "Ernest_Borgnine"
    "James_Coburn"
    "Sean_Connery"
    "Maia_Morgenstern"
    "Vincent_Cassel"
    "Barbra_Streisand"
    "Tony_Sirico"
    "Paul_Sorvino"
    "Reese_Witherspoon"
    "Jennifer_Aniston"
    "Marcello_Mastroianni"
    "Sandra_Bullock"
    "Hayden_Christensen"
    "Casey_Affleck"
    "Mary_McDonnell"
    "Zooey_Deschanel"
    "Tom_Berenger"
    "Tom_Sizemore"
    "Telly_Savalas"
    "Christopher_Lambert"
    "Christopher_Reeve"
    "Tom_Skerritt"
    "Karl-Otto_Alberty"
    "Edward_Fox_(actor)"
    "Michelle_Rodriguez"
    "Queen_Latifah"
    "Ewan_McGregor"
    "Asia_Argento"
    "Nick_Offerman"
    "Mandy_Patinkin"
    "Jeffrey_Wright"
    "Vera_Farmiga"
    "Jessica_Alba"
    "Alexis_Bledel"
    "Powers_Boothe"
    "Terence_Stamp|The Limey"
    "Bette_Midler"
    "Steve_Martin"
    "Chevy_Chase"
    "John_Candy"
    "Dan_Aykroyd"
    "Claire_Danes"
    "Glenn_Close"
    "Ian_McShane|John Wick 2"
    "Nina_Hoss|homeland german spy lady\nphoenix lead"
    "Stephen_McHattie|Pontypool\na history of violence"
    "Viggo_Mortensen"
    "Mathieu_Kassovitz|amelie\nmunich"
    "Sophie_Marceau|braveheart french princess"
    "Martin_Freeman"
    "Stephen_Fry"
    "John_Cleese"
    "Lorraine_Bracco"
    "Dean_Stockwell|yueh in dune\nsuave guy in blue velvet"
    "Jessica_Harper"
    "Isabella_Rossellini|blue velvet"
    "William_Shatner"
    "Dan_Hedaya|mulh.drv\nusual suspects some cop\nalien res general??"
    "Chad_Everett|mulh.drv older guy in diane's audition scene"
    'Spencer_Tracy|bad day at black rock\nguess whos coming to dinner'
    'Jeff_Daniels|the martian suit\nlooper gangster'
    'Alexander_Siddig|deep space nine dr bashir\nkingdom of heaven-blooms prisoner\ngot doran martell'
    'Kevin_Costner'
    "Lance_Henriksen"
    "Pete_Postlethwaite|usual suspects kobayshi\nalien3"
    "Isabelle_Adjani|la reine margot"
    "James_Woods"
    "Chazz_Palminteri| usual suspects\nanalyze this\na bronx tale"
    "Chris_Pratt|the magnificent 7 remake\nguardians of the galaxy &2"
    "Goldie_Hawn"
    "Iain_Glen|jorah mormont\nmultiple resident evil\nhamlet in rosenkrantz&guildenstern are dead"
    "James_Franco"
    "Rene_Russo"
    "Kevin_Bacon"
    "Bill_Paxton"
    "Gheorghe_Dinică"
    "Dragoș_Bucur"
    "Quentin_Tarantino"
    "Keri_Russel"
    "Robert_Loggia"
    "John_Wayne"
    "Ann_Dvorak"
    "Noah_Emmerich"
    "Steve_McQueen"
    "Morena_Baccarin"
    "Peter_Cushing"
    "Chris_Pine"
    "Robin_Wright"
    "Ann_Dowd"    
    "Julie_Christie"
    "Ian_McDiarmid"
    "Carrie_Coon|she's the gone girl"
    "Christopher_Eccleston|leftovers priest"
    "Kenneth_Branagh"
    "Sondra_Locke"
    "Rick_Moranis|ghostbusters, spaceballs"
    "Takeshi_Kitano|brother, ghost in the shell older police bossman guy dude"
    "Pilou Asbæk|leading cook in a hijacking, big dude with electronic eyes in ghost in the shell"
    "Jennifer_Tilly|gold digger on trial on liar liar\npoker lady btw"
    "Bill_Pullman|independence day president\nspaceballs lone starr\nlost highway lead"
    "Mel_Brooks"
    "Shia_LaBeuf|just do it"
    "John_Heard"    
    "David_Thewlis"
    "Ricky_Gervais"
    "Emily_Browning"
    "Elizabeth_Banks"
    "Jennifer_Lopez"
    "Michael_Cera"
    "Jean_Dujardin"
    "Pam_Grier"
    "Robert_Foster"
    "Jamie_Foxx|white house down\ncollateral\ndjango unchained"
    "Christoph_Waltz|django unchained\nnazi detective in inglorious basterds"
    "Michael_J._Fox"
    "Christopher_Lloyd"
    "Sebastian_Koch"
    "Anna_Kendrick|50/50 w/ cancer joseph gordon levit\nup in the air george clooney cynical air travelling business person falls in love with vera farmiga"
    "Andy_Garcia"
    "Robert_Mitchum"
    "Tony_Curtis"
    "Anthony_Perkins|k in the trial; norman bates in psycho(1960 - hitchcock)"
    "Mary_Elizabeth_Winstead|fargo 3 playgirl"
    "Ryan_Reynolds|deadpool"
    "Daniel_Kaluuya|black mirror suicidal; get out lead; sicario sidekick"
    "Julia_Stiles|bourne identity/supremacy/ultimatum\n mono lisa smile"
    "Natascha_McElhone|truman show\nronin\nsolaris\nira grill from the devil's own with ira terorrist dudes brad pitt and harrison ford"
    "Mark_Rylance|ready player one genius master guy\nbridge of spies quiet russian spy guy\ndunkirk older boat owner captain dude fellow"
)


actors=(
    "Sean_Young|chani in dune\nrachel in blade runner\nevil lieutenant in ace ventura"
    "Horst_Buchholz|magnificent 7, doctor lessing in la vita e bela"
) 




outf="image_links.txt"

rm "$outf"
touch "$outf"

#for foobar in "${actors[@]}"; do
#    IFS=| read foo txt <<< "$foobar"

for foobar in "${actors[@]}"; do

    IFS=\| read -r foo txt <<< "$foobar"

    if [[ ! -z $txt ]] ; then
	echo -e "$txt" > "$foo.gif.txt"
    fi

    wiki="https://en.wikipedia.org/wiki/$foo"

    rm a.htm

    echo "executing 'wget -q $wiki -O a.htm'"
    wget -q "$wiki" -O a.htm 

    echo "testing for existence"
    if [ -e a.htm -a -f a.htm -a -s a.htm ] ; then
	echo "WEB DOWNLOAD SUCCESS"
    else
	echo "WEB DOWNLOAD FAIL"
	continue
    fi

    link=$(grep -o -m 1 "src=\"//upload.wikimedia.org[^\"]*[jJ][pP][gG]" a.htm | cut -c 8-)
    echo "getting image:  $link"
    echo "$link" >> "$outf"
    wget -q "$link" -O "$foo.jpg"
    if [ -s "$foo.jpg" ] ; then
	echo "IMAGE DOWNLOAD SUCCESS"
    else
	if [ -f "$foo.jpg" ] ; then
	    rm "$foo.jpg"
	fi
	echo "IMAGE DOWNLOAD FAIL"
    fi
done

./make_new_gif.sh
